### ISSUE TITLE
Differentiate users who have not had a new decision announced in search

### ISSUE THREAD

**Issue by mahsu** [bigredhacks/bigredhacks-web#110]
So that we know who exactly is pending a decision so that it's easier to re-evaluate who was just accepted and waitlisted.

This can be done visually by highlighting the user's row in search.

**Comment by danluhuang** [comment]
solved by #146 . Added search filter option "Narrow by notification status", so we can just set that to "Pending" and the search result include only people who have not been notified of their decisions
