### ISSUE TITLE
Make Login Email Case Insensitive

### ISSUE THREAD

**Issue by mahsu** [bigredhacks/bigredhacks-web#163]
Login email should be case insensitive.

Include tests with fix

**Comment by TrevorEdwards** [comment]
We have code commented out that will do that, waiting for the end of this hackathon to deploy it

**Comment by mahsu** [comment]
Is there a reason we can't deploy it now?

**Comment by TrevorEdwards** [comment]
Couldn't deploy before due to some existing users who would be unable to login by the change without a db migration. We can now though
