### ISSUE TITLE
Convert site to post-hackathon version

### ISSUE THREAD

**Issue by TrevorEdwards** [bigredhacks/bigredhacks-web#190]
We should:
- [x] preserve the sponsors section
- [x] add a summary of the event
- [x] link to the devpost to show the submissions made
- [x] remove FAQ and any other irrelevant content
- [x] switch the clocktower to a thank you message of some sort

**Comment by TrevorEdwards** [comment]
@julianahhong Please delegate the bullets of this issue

**Comment by julianahhong** [comment]
Hackerearth link- https://bigredhacks2016.hackerearth.com/

**Comment by TrevorEdwards** [comment]
One issue came up- it looks like devpost changed its like style so the links will need to be updated before this is closed. Also need to merge the summary pr.
