### ISSUE TITLE
Fix Travis CI Config Vars

### ISSUE THREAD

**Issue by mahsu** [bigredhacks/bigredhacks-web#196]
Travis is currently crashing because of undefined/misdefined config vars.

**Comment by TrevorEdwards** [comment]
It looks like this was due to dots in our variable names like setup.cornell_auto_accept, etc. I'm changing the loader to only use the keys and not categories, and updating environment variables.

**Comment by mahsu** [comment]
Wait if that's the case it's a sign of regression. Can't find the original commit but all tests used to be passing.

Last time I checked it was because Travis was missing some config cars causing node to not be able to start up.

The config system should fully support for notation

**Comment by TrevorEdwards** [comment]
If you compare the new working build output to the broken, the broken has
an error for every dotted var. It is a bit unfortunate to lose the
categories again, but I'm not really sure if it's possible to allow for
dots. I'll take a look at the older working builds when I get a chance.
